from __future__ import annotations

from app.cities.base import CityColours, CityConfig, CityCoordinates, PostingSchedule, VenueTemplate

GLASGOW_CONFIG = CityConfig(
    slug="glasgow",
    city_name="Glasgow",
    brand_name="Gigged Glasgow",
    handle="@giggedglasgow",
    tagline="Your weekly Glasgow gig radar.",
    country="Scotland",
    timezone="Europe/London",
    colours=CityColours(primary="#d6f84c", secondary="#28b8a7", accent="#ef4d2f"),
    coordinates=CityCoordinates(latitude=55.8642, longitude=-4.2518),
    radius_km=24,
    hashtags=["#GiggedGlasgow", "#GlasgowGigs", "#GlasgowMusic", "#LiveMusic"],
    voice_notes=[
        "Direct, useful and music-first.",
        "Local but not forced; avoid cringe slang.",
        "Sharp gig-poster energy with clear city-guide detail.",
    ],
    default_posting_schedule=PostingSchedule(),
    venues=[
        VenueTemplate(name="Barrowland Ballroom", slug="barrowland-ballroom", address="244 Gallowgate", postcode="G4 0TT", capacity=1900, website_url="https://barrowland-ballroom.co.uk", instagram_handle="@thebarrowlands"),
        VenueTemplate(name="King Tut's Wah Wah Hut", slug="king-tuts-wah-wah-hut", address="272A St Vincent Street", postcode="G2 5RL", capacity=300, website_url="https://www.kingtuts.co.uk", instagram_handle="@kingtuts"),
        VenueTemplate(name="Saint Luke's", slug="st-lukes", address="17 Bain Street", postcode="G40 2JZ", capacity=650, website_url="https://www.stlukesglasgow.com", instagram_handle="@stlukesglasgow"),
        VenueTemplate(name="SWG3", slug="swg3", address="100 Eastvale Place", postcode="G3 8QG", capacity=1250, website_url="https://swg3.tv", instagram_handle="@swg3glasgow"),
        VenueTemplate(name="The Hug and Pint", slug="the-hug-and-pint", address="171 Great Western Road", postcode="G4 9AW", capacity=100, website_url="https://www.thehugandpint.com", instagram_handle="@thehugandpint"),
        VenueTemplate(name="Stereo", slug="stereo", address="22 Renfield Lane", postcode="G2 5AR", capacity=300, website_url="https://www.stereocafebar.com", instagram_handle="@stereoglasgow"),
        VenueTemplate(name="Mono", slug="mono", address="12 Kings Court", postcode="G1 5RB", capacity=300, website_url="https://www.monocafebar.com", instagram_handle="@monoglasgow"),
        VenueTemplate(name="Nice N Sleazy", slug="nice-n-sleazy", address="421 Sauchiehall Street", postcode="G2 3LG", capacity=160, website_url="https://www.nicensleazy.com", instagram_handle="@nicensleazy"),
        VenueTemplate(name="The Garage", slug="the-garage", address="490 Sauchiehall Street", postcode="G2 3LW", capacity=700, website_url="https://garageglasgow.co.uk", instagram_handle="@garageglasgow"),
        VenueTemplate(name="OVO Hydro", slug="ovo-hydro", address="Exhibition Way", postcode="G3 8YW", capacity=14000, website_url="https://www.ovohydro.com", instagram_handle="@ovohydro"),
        VenueTemplate(name="Oran Mor", slug="oran-mor", address="Byres Road", postcode="G12 8QX", capacity=500, website_url="https://oran-mor.co.uk", instagram_handle="@oranmorglasgow"),
        VenueTemplate(name="Broadcast", slug="broadcast", address="427 Sauchiehall Street", postcode="G2 3LG", capacity=200, website_url="https://broadcastglasgow.com", instagram_handle="@broadcastglasgow"),
    ],
    venue_whitelist=[
        "barrowland-ballroom",
        "king-tuts-wah-wah-hut",
        "st-lukes",
        "swg3",
        "the-hug-and-pint",
        "stereo",
        "mono",
        "nice-n-sleazy",
        "the-garage",
        "ovo-hydro",
        "oran-mor",
        "broadcast",
    ],
    genre_filters=[
        "alternative",
        "electronic",
        "folk",
        "hip-hop",
        "indie",
        "jazz",
        "metal",
        "pop",
        "punk",
        "rock",
        "soul",
    ],
    minimum_date_range_days=14,
    weekly_roundup_start="friday",
    weekly_roundup_end="thursday",
)
